spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loginp
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ secret.EMAIL }
    password: ${ secret.PASSWORD }
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

logging:
  level:
    org:
      hibernate:
        type: trace
