DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS email CASCADE;

CREATE TABLE usuario (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	telefone VARCHAR(15),
	senha VARCHAR(500) NOT NULL,
	foto TEXT NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	atualizado_em TIMESTAMP,
	ativo BOOLEAN NOT null,
	reset_password_token varchar(50)
);


CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	funcao VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;


CREATE TABLE email (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	remetente VARCHAR(255) NOT NULL,
	email_from VARCHAR(255) NOT NULL,
	email_to VARCHAR(255) NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	mensagem TEXT NOT NULL,
	enviado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	status_email VARCHAR(7) NOT null,
	CONSTRAINT check_email_remetente_destinatario check (email_from != email_to),
	CONSTRAINT check_email_status_email check (status_email in ('SUCESSO', 'ERRO'))
);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('puma', 'puma@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('henrique', 'henrique@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);


INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste', 'teste@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 2', 'teste2@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 3', 'teste3@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 4', 'teste4@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 5', 'teste5@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 6', 'teste6@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 7', 'teste7@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 8', 'teste8@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 9', 'teste9@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);

INSERT INTO usuario(nome, email, telefone, senha, foto, criado_em, ativo)
VALUES('teste 10', 'teste10@gmail.com', '51912345678', '$2a$10$vpa15jnEy7H8VMEkJcza/uyJdNUpMxPEwynzW0N.LHgMKJUm6D1yW', 'https://tm.ibxk.com.br/2017/06/22/22100428046161.jpg', CURRENT_TIMESTAMP, true);


insert into permissao (funcao, usuario_id) values ('USUARIO', 1);
insert into permissao (funcao, usuario_id) values ('ADMIN', 1);
insert into permissao (funcao, usuario_id) values ('ADMIN', 2);

insert into permissao (funcao, usuario_id) values ('USUARIO', 3);
insert into permissao (funcao, usuario_id) values ('USUARIO', 4);
insert into permissao (funcao, usuario_id) values ('USUARIO', 5);
insert into permissao (funcao, usuario_id) values ('USUARIO', 6);
insert into permissao (funcao, usuario_id) values ('USUARIO', 7);
insert into permissao (funcao, usuario_id) values ('USUARIO', 8);
insert into permissao (funcao, usuario_id) values ('USUARIO', 9);
insert into permissao (funcao, usuario_id) values ('USUARIO', 10);
insert into permissao (funcao, usuario_id) values ('USUARIO', 11);
insert into permissao (funcao, usuario_id) values ('USUARIO', 12);


