DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS email CASCADE;

CREATE TABLE usuario (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	telefone VARCHAR(15),
	senha VARCHAR(500) NOT NULL,
	foto TEXT NOT NULL,
	funcao VARCHAR(15) NOT null,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	atualizado_em TIMESTAMP,
	ativo BOOLEAN NOT null,
	reset_password_token varchar(50)
	CONSTRAINT check_usuario_funcao check (funcao in ('ADMIN', 'USER'))
);


CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	funcao VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);


CREATE TABLE email (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	remetente VARCHAR(255) NOT NULL,
	email_from VARCHAR(255) NOT NULL,
	email_to VARCHAR(255) NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	mensagem TEXT NOT NULL,
	enviado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	status_email VARCHAR(7) NOT null,
	CONSTRAINT check_email_remetente_destinatario check (email_from != email_to),
	CONSTRAINT check_email_status_email check (status_email in ('SUCESSO', 'ERRO'))
);